# Based on .travis.yml in `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)

sudo: true

os:
  - linux
  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_PKG=true   # Use the latest version from the default package manager
    - LAZ_VER=1.0.14 # Use specific (binary) release
    - LAZ_VER=1.2.6
    - LAZ_VER=1.4.4

matrix:
  allow_failures:
    - env: LAZ_PKG=true
    - env: LAZ_VER=1.0.14
    - env: LAZ_VER=1.2.6
    - os: osx
  include:
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_WINE=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_WINE=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"

before_install:
    # Start virtual display server
  - sh -e /etc/init.d/xvfb start || true
  - sudo apt-get update && sudo apt-get install libxtst-dev libkeybinder-dev || true

install:
    # Install prerequisites (wine/fpc/lazarus)
  - ./autobuild/travis-lazarus/.travis.install.py

script:
  - $LAZ_WINE lazbuild $LAZ_OPT ./Projects/Simba/Simba.lpi
